// Icon font mapping generated from your output/icons.json
// Each icon maps to its Unicode character in the font
export type FoodIconData = {
  id: FoodIcons;
  name: string;
  category: string;
};

export const CATEGORY_TRANSLATIONS = {
  all: 'Toutes les catégories',
  fruits: 'Fruits',
  vegetables: 'Légumes',
  nuts: 'Noix',
  dairy: 'Produits laitiers et œufs',
  meat: 'Viande',
  seafood: 'Fruits de mer',
  desserts: 'Desserts et sucreries',
  beverages: 'Boissons',
  grains: 'Pain et céréales',
  condiments: 'Condiments et épices',
  snacks: 'Snacks',
  other: 'Autre',
} as const;

export type Category = keyof typeof CATEGORY_TRANSLATIONS;

export const ICON_FONT_MAP: Record<string, [string, string, Category]> = {
  wine_2: ['f101', 'Vin', 'beverages'],
  wine: ['f102', 'Vin', 'beverages'],
  whole_grain_bread: ['f103', 'Pain complet', 'grains'],
  whisky_2: ['f104', 'Whisky', 'beverages'],
  whisky: ['f105', 'Whisky', 'beverages'],
  weeding_cake: ['f106', 'Gâteau de mariage', 'desserts'],
  watermelon_split: ['f107', 'Pastèque (tranchée)', 'fruits'],
  watermelon_slice: ['f108', 'Pastèque (partie)', 'fruits'],
  watermelon: ['f109', 'Pastèque', 'fruits'],
  walnut: ['f10a', 'Noix', 'nuts'],
  waffle_2: ['f10b', 'Gaufre', 'desserts'],
  wafer: ['f10c', 'Gaufrette', 'desserts'],
  turnip: ['f10d', 'Navet', 'vegetables'],
  tomato_split: ['f10e', 'Tomate (tranchée)', 'vegetables'],
  tomato: ['f10f', 'Tomate', 'vegetables'],
  toast_marmalade: ['f110', 'Toast confiture', 'grains'],
  toast: ['f111', 'Toast', 'grains'],
  teapot: ['f112', 'Théière', 'other'],
  tea_kettle: ['f113', 'Bouilloire', 'other'],
  tea_bag: ['f114', 'Sachet de thé', 'beverages'],
  tea: ['f115', 'Thé', 'beverages'],
  tangerine: ['f116', 'Mandarine', 'fruits'],
  t_bone_steak: ['f117', 'Steak T-bone', 'meat'],
  sweet_potato: ['f118', 'Patate douce', 'vegetables'],
  sushi_nigiri: ['f119', 'Sushi nigiri', 'seafood'],
  sushi_maki: ['f11a', 'Sushi maki', 'seafood'],
  sugarcane: ['f11b', 'Canne à sucre', 'vegetables'],
  sugar_cubes: ['f11c', 'Cubes de sucre', 'condiments'],
  sugar_cube: ['f11d', 'Cube de sucre', 'condiments'],
  strawberry_jam: ['f11e', 'Confiture de fraises', 'condiments'],
  strawberry: ['f11f', 'Fraise', 'fruits'],
  steak: ['f120', 'Steak', 'meat'],
  squash_split: ['f121', 'Courge (tranchée)', 'vegetables'],
  squash: ['f122', 'Courge', 'vegetables'],
  spicy: ['f123', 'Épicé', 'condiments'],
  spaghetti: ['f124', 'Spaghetti', 'grains'],
  soup: ['f125', 'Soupe', 'beverages'],
  soft_cream_cone_2: ['f126', 'Cornet de crème glacée', 'desserts'],
  soft_cream_cone: ['f127', 'Cornet de crème glacée', 'desserts'],
  soda_can: ['f128', 'Canette de soda', 'beverages'],
  sliced_bread: ['f129', 'Pain tranché', 'grains'],
  skewer: ['f12a', 'Brochette', 'meat'],
  shrimp: ['f12b', 'Crevette', 'seafood'],
  shot_glass_2: ['f12c', 'Verre à shot', 'beverages'],
  shot_glass: ['f12d', 'Verre à shot', 'beverages'],
  sausage: ['f12e', 'Saucisse', 'meat'],
  salt_shaker: ['f12f', 'Salière', 'condiments'],
  salt: ['f130', 'Sel', 'condiments'],
  salad: ['f131', 'Salade', 'vegetables'],
  romaine_lettuce: ['f132', 'Laitue romaine', 'vegetables'],
  rollcake: ['f133', 'Gâteau roulé', 'desserts'],
  rocket_popsicle: ['f134', 'Popsicle roquette', 'desserts'],
  rock_candy: ['f135', 'Sucre d’orge', 'desserts'],
  roasted_chicken: ['f136', 'Poulet rôti', 'meat'],
  rice_cracker: ['f137', 'Galette de riz', 'snacks'],
  red_pitahaya: ['f138', 'Fruit du dragon rouge', 'fruits'],
  raspberry: ['f139', 'Framboise', 'fruits'],
  radish: ['f13a', 'Radis', 'vegetables'],
  pumpkin_split: ['f13b', 'Courge (tranchée)', 'vegetables'],
  pumpkin: ['f13c', 'Courge', 'vegetables'],
  pretzel: ['f13d', 'Bretzel', 'snacks'],
  poultry: ['f13e', 'Volaille', 'meat'],
  potato: ['f13f', 'Pomme de terre', 'vegetables'],
  portobello: ['f140', 'Portobello', 'vegetables'],
  pork: ['f141', 'Porc', 'meat'],
  popsicle_double: ['f142', 'Sucette double', 'desserts'],
  popsicle: ['f143', 'Sucette', 'desserts'],
  popcorn: ['f144', 'Popcorn', 'snacks'],
  plum_split: ['f145', 'Prune (tranchée)', 'fruits'],
  plum: ['f146', 'Prune', 'fruits'],
  pizza_round: ['f147', 'Pizza (ronde)', 'snacks'],
  pizza: ['f148', 'Pizza', 'snacks'],
  pitahaya: ['f149', 'Fruit du dragon', 'fruits'],
  pistachios: ['f14a', 'Pistaches', 'nuts'],
  pineapple_2: ['f14b', 'Ananas', 'fruits'],
  pineapple: ['f14c', 'Ananas', 'fruits'],
  pie_slice: ['f14d', 'Part de tarte', 'desserts'],
  pie_2: ['f14e', 'Tarte', 'desserts'],
  pie: ['f14f', 'Tarte', 'desserts'],
  pickles: ['f150', 'Cornichons', 'condiments'],
  pepper_shaker: ['f151', 'Epices', 'condiments'],
  pepper_grinder: ['f152', 'Moulin à poivre', 'condiments'],
  pecan: ['f153', 'Pécan', 'nuts'],
  peas: ['f154', 'Pois', 'vegetables'],
  pear_split: ['f155', 'Poire (tranchée)', 'fruits'],
  pear: ['f156', 'Poire', 'fruits'],
  peanut_butter: ['f157', 'Beurre de cacahuète', 'condiments'],
  peanut: ['f158', 'Cacahuète', 'nuts'],
  peach_split: ['f159', 'Pêche (tranchée)', 'fruits'],
  peach: ['f15a', 'Pêche', 'fruits'],
  papaya: ['f15b', 'Papaye', 'fruits'],
  pancakes: ['f15c', 'Pancakes', 'desserts'],
  pancake: ['f15d', 'Crêpe', 'desserts'],
  orange_split: ['f15e', 'Orange (tranchée)', 'fruits'],
  orange: ['f15f', 'Orange', 'fruits'],
  onion: ['f160', 'Oignon', 'vegetables'],
  omelette: ['f161', 'Omelette', 'meat'],
  olives: ['f162', 'Olives', 'vegetables'],
  olive_oil: ['f163', 'Huile d’olive', 'condiments'],
  noodles: ['f164', 'Nouilles', 'grains'],
  mustard: ['f165', 'Moutarde', 'condiments'],
  mushrooms_2: ['f166', 'Champignons', 'vegetables'],
  mushrooms: ['f167', 'Champignons', 'vegetables'],
  muffin: ['f168', 'Muffin', 'desserts'],
  milkshake: ['f169', 'Milkshake', 'dairy'],
  milk: ['f16a', 'Lait', 'dairy'],
  meatballs_2: ['f16b', 'Boulettes de viande', 'meat'],
  meatballs: ['f16c', 'Dinde', 'meat'],
  mayonnaise: ['f16d', 'Mayonnaise', 'condiments'],
  martini: ['f16e', 'Martini', 'beverages'],
  marshmallow: ['f16f', 'Guimauve', 'desserts'],
  margarita: ['f170', 'Margarita', 'beverages'],
  maple_syrup_bottle: ['f171', 'Bouteille de sirop d’érable', 'condiments'],
  maple_syrup: ['f172', 'Sirop d’érable', 'condiments'],
  macaron: ['f173', 'Macaron', 'desserts'],
  macadamia_nuts: ['f174', 'Noix de macadamia', 'nuts'],
  lollipop: ['f175', 'Sucette', 'desserts'],
  lobster: ['f176', 'Homard', 'seafood'],
  lime_2: ['f177', 'Citron vert', 'fruits'],
  lime: ['f178', 'Citron vert', 'fruits'],
  lettuce: ['f179', 'Laitue', 'vegetables'],
  lentils: ['f17a', 'Lentilles', 'grains'],
  lemon_2: ['f17b', 'Citron', 'fruits'],
  lemon: ['f17c', 'Citron', 'fruits'],
  leek: ['f17d', 'Poireau', 'vegetables'],
  kiwi: ['f17e', 'Kiwi', 'fruits'],
  ketchup: ['f17f', 'Ketchup', 'condiments'],
  jar: ['f180', 'Bocal', 'other'],
  ice_cubes: ['f181', 'Glaçons', 'other'],
  ice_cream_double_cone: ['f182', 'Cornet de glace double', 'desserts'],
  ice_cream_cup_2: ['f183', 'Coupe de glace', 'desserts'],
  ice_cream_cup: ['f184', 'Coupe de glace', 'desserts'],
  ice_cream_cone_2: ['f185', 'Cornet de glace', 'desserts'],
  ice_cream_cone: ['f186', 'Cornet de glace', 'desserts'],
  ice_cream_bar: ['f187', 'Barre de glace', 'desserts'],
  ice_cream: ['f188', 'Glace', 'desserts'],
  hotdog: ['f189', 'Hot-dog', 'snacks'],
  hot_chocolate: ['f18a', 'Chocolat chaud', 'beverages'],
  honey: ['f18b', 'Miel', 'condiments'],
  hazelnuts: ['f18c', 'Noisettes', 'nuts'],
  hard_boiled_egg: ['f18d', 'Œuf dur', 'dairy'],
  hamburger: ['f18e', 'Hamburger', 'meat'],
  ham: ['f18f', 'Jambon', 'meat'],
  green_beans: ['f190', 'Haricots verts', 'vegetables'],
  grapes_2: ['f191', 'Raisins', 'fruits'],
  grapes: ['f192', 'Raisins', 'fruits'],
  grapefruit_2: ['f193', 'Pamplemousse', 'fruits'],
  grapefruit: ['f194', 'Pamplemousse', 'fruits'],
  goldenberries: ['f195', 'Baies dorées', 'fruits'],
  glass_2: ['f196', 'Verre', 'other'],
  glass: ['f197', 'Verre', 'other'],
  garlic: ['f198', 'Ail', 'vegetables'],
  frozen_2: ['f199', 'Surgelés', 'other'],
  frozen: ['f19a', 'Froid', 'other'],
  fried_egg_2: ['f19b', 'Œuf sur le plat', 'dairy'],
  fried_egg: ['f19c', 'Œuf sur le plat', 'dairy'],
  french_fries: ['f19d', 'Frites', 'snacks'],
  flour: ['f19e', 'Farine', 'grains'],
  fish_steak: ['f19f', 'Steak de poisson', 'seafood'],
  fish_filet: ['f1a0', 'Filet de poisson', 'seafood'],
  fish: ['f1a1', 'Poisson', 'seafood'],
  fig_2: ['f1a2', 'Figue', 'fruits'],
  fig: ['f1a3', 'Figue', 'fruits'],
  eggplant: ['f1a4', 'Aubergine', 'vegetables'],
  egg: ['f1a5', 'Œuf', 'dairy'],
  eclair: ['f1a6', 'Éclair', 'desserts'],
  doughnut_3: ['f1a7', 'Doughnut', 'desserts'],
  doughnut_2: ['f1a8', 'Doughnut', 'desserts'],
  doughnut: ['f1a9', 'Doughnut', 'desserts'],
  cutlet: ['f1aa', 'Escalope', 'meat'],
  cupcake: ['f1ab', 'Cupcake', 'desserts'],
  cucumber_2: ['f1ac', 'Concombre', 'vegetables'],
  cucumber: ['f1ad', 'Concombre', 'vegetables'],
  croissant: ['f1ae', 'Croissant', 'desserts'],
  cranberries: ['f1af', 'Canneberges', 'fruits'],
  cracker: ['f1b0', 'Cracker', 'snacks'],
  crab: ['f1b1', 'Crabe', 'seafood'],
  cotton_candy_2: ['f1b2', 'Barbe à papa', 'desserts'],
  cotton_candy: ['f1b3', 'Barbe à papa', 'desserts'],
  corn: ['f1b4', 'Maïs', 'vegetables'],
  cookie_3: ['f1b5', 'Cookie', 'desserts'],
  cookie_1: ['f1b6', 'Cookie', 'desserts'],
  cookie5: ['f1b7', 'Cookie', 'desserts'],
  cookie4: ['f1b8', 'Cookie', 'desserts'],
  cookie: ['f1b9', 'Cookie', 'desserts'],
  cognac: ['f1ba', 'Cognac', 'beverages'],
  coffee_pot: ['f1bb', 'Cafetière', 'beverages'],
  coffee_bean: ['f1bc', 'Grains de café', 'nuts'],
  coffee: ['f1bd', 'Café', 'beverages'],
  coconut_split_2: ['f1be', 'Noix de coco (tranchée)', 'fruits'],
  coconut_split: ['f1bf', 'Noix de coco (tranchée)', 'fruits'],
  coconut: ['f1c0', 'Noix de coco', 'fruits'],
  cocoa: ['f1c1', 'Cacao', 'nuts'],
  cocktail: ['f1c2', 'Cocktail', 'beverages'],
  cinnamon: ['f1c3', 'Cannelle', 'nuts'],
  chopsticks_bowl: ['f1c4', 'Bol avec des baguettes', 'other'],
  chocolate_chip_cookie: ['f1c5', 'Cookie aux pépites de chocolat', 'desserts'],
  chocolate_bonbon: ['f1c6', 'Bonbon au chocolat', 'desserts'],
  chocolate_bar: ['f1c7', 'Barre de chocolat', 'desserts'],
  chocolate: ['f1c8', 'Chocolat', 'desserts'],
  chili_pepper: ['f1c9', 'Piment', 'vegetables'],
  chickpeas: ['f1ca', 'Pois chiches', 'vegetables'],
  chicken_leg_fried: ['f1cb', 'Cuisse de poulet frite', 'meat'],
  chicken_leg: ['f1cc', 'Cuisse de poulet', 'meat'],
  chestnut: ['f1cd', 'Châtaigne', 'nuts'],
  cherry_tomatoes: ['f1ce', 'Tomates cerises', 'vegetables'],
  cherries: ['f1cf', 'Cerises', 'fruits'],
  cheese: ['f1d0', 'Fromage', 'dairy'],
  champagne: ['f1d1', 'Champagne', 'beverages'],
  cellery: ['f1d2', 'Céleri', 'vegetables'],
  cauliflower: ['f1d3', 'Chou-fleur', 'vegetables'],
  cassava: ['f1d4', 'Manioc', 'vegetables'],
  cashew_nuts: ['f1d5', 'Noix de cajou', 'nuts'],
  carrot: ['f1d6', 'Carotte', 'vegetables'],
  caramel_apple: ['f1d7', 'Pomme au caramel', 'desserts'],
  cantaloupe_slice: ['f1d8', 'Melon (tranché)', 'fruits'],
  cantaloupe: ['f1d9', 'Melon', 'fruits'],
  candy_cane: ['f1da', 'Canne en sucre', 'desserts'],
  candy: ['f1db', 'Bonbon', 'desserts'],
  cake_slice_nuts: ['f1dc', 'Part de gâteau aux noix', 'desserts'],
  cake_slice: ['f1dd', 'Part de gâteau', 'desserts'],
  cake: ['f1de', 'Gâteau', 'desserts'],
  cabbage: ['f1df', 'Chou', 'vegetables'],
  butter: ['f1e0', 'Beurre', 'dairy'],
  bun: ['f1e1', 'Petit pain', 'grains'],
  bubblegum_machine: ['f1e2', 'Distributeur de chewing-gum', 'snacks'],
  bubblegum: ['f1e3', 'Chewing-gum', 'snacks'],
  brown_bread: ['f1e4', 'Pain complet', 'grains'],
  broccoli: ['f1e5', 'Brocoli', 'vegetables'],
  bread_slice: ['f1e6', 'Tranche de pain', 'grains'],
  bread: ['f1e7', 'Pain', 'grains'],
  brazil_nuts: ['f1e8', 'Noix du Brésil', 'nuts'],
  bottle_wine: ['f1e9', 'Bouteille de vin', 'beverages'],
  bottle_scotch_2: ['f1ea', 'Bouteille de scotch', 'beverages'],
  bottle_scotch: ['f1eb', 'Bouteille de scotch', 'beverages'],
  bottle_gallon: ['f1ec', 'Grosse bouteille', 'other'],
  blueberries: ['f1ed', 'Myrtilles', 'fruits'],
  blackberry: ['f1ee', 'Mûre', 'fruits'],
  biscuit: ['f1ef', 'Biscuit', 'snacks'],
  biscotti: ['f1f0', 'Biscotti', 'snacks'],
  birthday_cake: ['f1f1', "Gâteau d'anniversaire", 'desserts'],
  bell_pepper_split: ['f1f2', 'Poivron (tranché)', 'vegetables'],
  bell_pepper: ['f1f3', 'Poivron', 'vegetables'],
  beetroot: ['f1f4', 'Betterave', 'vegetables'],
  beef: ['f1f5', 'Bœuf', 'meat'],
  beans: ['f1f6', 'Haricots', 'vegetables'],
  banana_split: ['f1f7', 'Banana split', 'desserts'],
  banana_peeled: ['f1f8', 'Banane (pelée)', 'fruits'],
  banana: ['f1f9', 'Banane', 'fruits'],
  bacon: ['f1fa', 'Bacon', 'meat'],
  avocado_split: ['f1fb', 'Avocat (tranché)', 'fruits'],
  avocado: ['f1fc', 'Avocat', 'fruits'],
  asparagus: ['f1fd', 'Asperge', 'vegetables'],
  artichoke: ['f1fe', 'Artichaut', 'vegetables'],
  apple_split: ['f1ff', 'Pomme (tranchée)', 'fruits'],
  apple_green_split: ['f200', 'Pomme verte (tranchée)', 'fruits'],
  apple_green: ['f201', 'Pomme verte', 'fruits'],
  apple: ['f202', 'Pomme', 'fruits'],
  almonds: ['f203', 'Amandes', 'nuts'],
  almond: ['f204', 'Amande', 'nuts'],
} as const;

export type FoodIcons = keyof typeof ICON_FONT_MAP;

// Helper function to get CSS class name for an icon
export const getIconClass = (iconId: FoodIcons): string => {
  return `food-icon food-icon-${iconId}`;
};

// Helper function to get Unicode character for an icon
export const getIconUnicode = (iconId: FoodIcons): string => {
  return ICON_FONT_MAP[iconId]?.[0] || 'f000'; // fallback
};

export const getIconData = (iconId: FoodIcons): FoodIconData | undefined => {
  const icon = ICON_FONT_MAP[iconId];
  if (!icon) return undefined;

  const [_, name, category] = icon;
  return { id: iconId, name, category };
};

// Export the data
export const ICON_DATA: FoodIconData[] = Object.entries(ICON_FONT_MAP)
  .map(([id, [unicode, name, category]]) => ({
    id: id as FoodIcons,
    unicode,
    name,
    category: CATEGORY_TRANSLATIONS[category],
  }))
  .toSorted((a, b) => a.name.localeCompare(b.name));
