// Icon font mapping generated from your output/icons.json
// Each icon maps to its Unicode character in the font
export type FoodIconData = {
  id: FoodIcons;
  name: string;
  category: string;
};

export const CATEGORY_TRANSLATIONS = {
  all: 'Toutes les catégories',
  fruits: 'Fruits',
  vegetables: 'Légumes',
  nuts: 'Noix',
  dairy: 'Produits laitiers et œufs',
  meat: 'Viande',
  seafood: 'Fruits de mer',
  desserts: 'Desserts et sucreries',
  beverages: 'Boissons',
  grains: 'Pain et céréales',
  condiments: 'Condiments et épices',
  snacks: 'Snacks',
  other: 'Autre',
} as const;

export type Category = keyof typeof CATEGORY_TRANSLATIONS;

export const ICON_FONT_MAP: Record<string, [string, Category]> = {
  wine_2: ['Vin', 'beverages'],
  wine: ['Vin', 'beverages'],
  whole_grain_bread: ['Pain complet', 'grains'],
  'white-circle': ['Mozzarella', 'dairy'],
  whisky_2: ['Whisky', 'beverages'],
  whisky: ['Whisky', 'beverages'],
  weeding_cake: ['Gâteau de mariage', 'desserts'],
  watermelon_split: ['Pastèque (tranchée)', 'fruits'],
  watermelon_slice: ['Pastèque (partie)', 'fruits'],
  watermelon: ['Pastèque', 'fruits'],
  walnut: ['Noix', 'nuts'],
  waffle_2: ['Gaufre', 'desserts'],
  wafer: ['Gaufrette', 'desserts'],
  turnip: ['Navet', 'vegetables'],
  'tropical-drink': ['Jus de fruit', 'beverages'],
  toothbrush: ['Brosse à dents', 'other'],
  tomato_split: ['Tomate (tranchée)', 'vegetables'],
  tomato: ['Tomate', 'vegetables'],
  toast_marmalade: ['Toast confiture', 'grains'],
  toast: ['Toast', 'grains'],
  teapot: ['Théière', 'other'],
  tea_kettle: ['Bouilloire', 'other'],
  tea_bag: ['Sachet de thé', 'beverages'],
  tea: ['Thé', 'beverages'],
  tangerine: ['Mandarine', 'fruits'],
  t_bone_steak: ['Steak T-bone', 'meat'],
  sweet_potato: ['Patate douce', 'vegetables'],
  sushi_nigiri: ['Sushi nigiri', 'seafood'],
  sushi_maki: ['Sushi maki', 'seafood'],
  sugarcane: ['Canne à sucre', 'vegetables'],
  sugar_cubes: ['Cubes de sucre', 'condiments'],
  sugar_cube: ['Cube de sucre', 'condiments'],
  strawberry_jam: ['Confiture de fraises', 'condiments'],
  strawberry: ['Fraise', 'fruits'],
  steak: ['Steak', 'meat'],
  squash_split: ['Courge (tranchée)', 'vegetables'],
  squash: ['Courge', 'vegetables'],
  sponge: ['Éponge', 'other'],
  spicy: ['Épicé', 'condiments'],
  spaghetti: ['Spaghetti', 'grains'],
  soup: ['Soupe', 'beverages'],
  soft_cream_cone_2: ['Cornet de crème glacée', 'desserts'],
  soft_cream_cone: ['Cornet de crème glacée', 'desserts'],
  soda_can: ['Canette de soda', 'beverages'],
  soap: ['Savon', 'other'],
  'sneezing-face': ['Mouchoir', 'other'],
  sliced_bread: ['Pain tranché', 'grains'],
  skewer: ['Brochette', 'meat'],
  shrimp: ['Crevette', 'seafood'],
  shot_glass_2: ['Verre à shot', 'beverages'],
  shot_glass: ['Verre à shot', 'beverages'],
  'sheaf-of-rice': ['Barre de céréales', 'grains'],
  'shallow-pan-of-food': ['Semoule', 'grains'],
  sausage: ['Saucisse', 'meat'],
  salt_shaker: ['Salière', 'condiments'],
  salt: ['Sel', 'condiments'],
  salad: ['Salade', 'vegetables'],
  sake: ['Fromage blanc', 'dairy'],
  romaine_lettuce: ['Laitue romaine', 'vegetables'],
  rollcake: ['Gâteau roulé', 'desserts'],
  'roll-of-paper': ['Papier toilette', 'other'],
  rocket_popsicle: ['Popsicle roquette', 'desserts'],
  rock_candy: ['Sucre d’orge', 'desserts'],
  roasted_chicken: ['Poulet rôti', 'meat'],
  rice_cracker: ['Galette de riz', 'snacks'],
  red_pitahaya: ['Fruit du dragon rouge', 'fruits'],
  raspberry: ['Framboise', 'fruits'],
  ram: ['Fromage feta', 'dairy'],
  radish: ['Radis', 'vegetables'],
  pumpkin_split: ['Courge (tranchée)', 'vegetables'],
  pumpkin: ['Courge', 'vegetables'],
  pretzel: ['Bretzel', 'snacks'],
  poultry: ['Volaille', 'meat'],
  potato: ['Pomme de terre', 'vegetables'],
  portobello: ['Portobello', 'vegetables'],
  pork: ['Porc', 'meat'],
  popsicle_double: ['Sucette double', 'desserts'],
  popsicle: ['Sucette', 'desserts'],
  popcorn: ['Popcorn', 'snacks'],
  plum_split: ['Prune (tranchée)', 'fruits'],
  plum: ['Prune', 'fruits'],
  pizza_round: ['Pizza (ronde)', 'snacks'],
  pizza: ['Pizza', 'snacks'],
  pitahaya: ['Fruit du dragon', 'fruits'],
  pistachios: ['Pistaches', 'nuts'],
  pineapple_2: ['Ananas', 'fruits'],
  pineapple: ['Ananas', 'fruits'],
  pie_slice: ['Part de tarte', 'desserts'],
  pie_2: ['Tarte', 'desserts'],
  pie: ['Tarte', 'desserts'],
  pickles: ['Cornichons', 'condiments'],
  pepper_shaker: ['Epices', 'condiments'],
  pepper_grinder: ['Moulin à poivre', 'condiments'],
  pecan: ['Pécan', 'nuts'],
  peas: ['Pois', 'vegetables'],
  pear_split: ['Poire (tranchée)', 'fruits'],
  pear: ['Poire', 'fruits'],
  peanut_butter: ['Beurre de cacahuète', 'condiments'],
  peanut: ['Cacahuète', 'nuts'],
  peach_split: ['Pêche (tranchée)', 'fruits'],
  peach: ['Pêche', 'fruits'],
  papaya: ['Papaye', 'fruits'],
  pancakes: ['Pancakes', 'desserts'],
  pancake: ['Crêpe', 'desserts'],
  orange_split: ['Orange (tranchée)', 'fruits'],
  orange: ['Orange', 'fruits'],
  onion: ['Oignon', 'vegetables'],
  omelette: ['Omelette', 'meat'],
  olives: ['Olives', 'vegetables'],
  olive_oil: ['Huile d’olive', 'condiments'],
  noodles: ['Nouilles', 'grains'],
  mustard: ['Moutarde', 'condiments'],
  mushrooms_2: ['Champignons', 'vegetables'],
  mushrooms: ['Champignons', 'vegetables'],
  muffin: ['Muffin', 'desserts'],
  milkshake: ['Milkshake', 'dairy'],
  milk: ['Lait', 'dairy'],
  meatballs_2: ['Boulettes de viande', 'meat'],
  meatballs: ['Dinde', 'meat'],
  mayonnaise: ['Mayonnaise', 'condiments'],
  martini: ['Martini', 'beverages'],
  marshmallow: ['Guimauve', 'desserts'],
  margarita: ['Margarita', 'beverages'],
  maple_syrup_bottle: ['Bouteille de sirop d’érable', 'condiments'],
  maple_syrup: ['Sirop d’érable', 'condiments'],
  'magic-wand': ['Masque de soin', 'other'],
  macaron: ['Macaron', 'desserts'],
  macadamia_nuts: ['Noix de macadamia', 'nuts'],
  'lotion-bottle': ['Shampoing', 'other'],
  lollipop: ['Sucette', 'desserts'],
  lobster: ['Homard', 'seafood'],
  lime_2: ['Citron vert', 'fruits'],
  lime: ['Citron vert', 'fruits'],
  lettuce: ['Laitue', 'vegetables'],
  lentils: ['Lentilles', 'grains'],
  lemon_2: ['Citron', 'fruits'],
  lemon: ['Citron', 'fruits'],
  leek: ['Poireau', 'vegetables'],
  'leaf-fluttering-in-wind': ['Basilic', 'vegetables'],
  kiwi: ['Kiwi', 'fruits'],
  ketchup: ['Ketchup', 'condiments'],
  jar: ['Bocal', 'other'],
  ice_cubes: ['Glaçons', 'other'],
  ice_cream_double_cone: ['Cornet de glace double', 'desserts'],
  ice_cream_cup_2: ['Coupe de glace', 'desserts'],
  ice_cream_cup: ['Coupe de glace', 'desserts'],
  ice_cream_cone_2: ['Cornet de glace', 'desserts'],
  ice_cream_cone: ['Cornet de glace', 'desserts'],
  ice_cream_bar: ['Barre de glace', 'desserts'],
  ice_cream: ['Glace', 'desserts'],
  hotdog: ['Hot-dog', 'snacks'],
  hot_chocolate: ['Chocolat chaud', 'beverages'],
  honey: ['Miel', 'condiments'],
  hazelnuts: ['Noisettes', 'nuts'],
  hard_boiled_egg: ['Œuf dur', 'dairy'],
  hamburger: ['Hamburger', 'meat'],
  ham: ['Jambon', 'meat'],
  green_beans: ['Haricots verts', 'vegetables'],
  grapes_2: ['Raisins', 'fruits'],
  grapes: ['Raisins', 'fruits'],
  grapefruit_2: ['Pamplemousse', 'fruits'],
  grapefruit: ['Pamplemousse', 'fruits'],
  goldenberries: ['Baies dorées', 'fruits'],
  glass_2: ['Verre', 'other'],
  glass: ['Verre', 'other'],
  'glass-of-milk': ['Yaourts', 'dairy'],
  garlic: ['Ail', 'vegetables'],
  frozen_2: ['Surgelés', 'other'],
  frozen: ['Froid', 'other'],
  fried_egg_2: ['Œuf sur le plat', 'dairy'],
  fried_egg: ['Œuf sur le plat', 'dairy'],
  french_fries: ['Frites', 'snacks'],
  flour: ['Farine', 'grains'],
  fish_steak: ['Steak de poisson', 'seafood'],
  fish_filet: ['Filet de poisson', 'seafood'],
  fish: ['Poisson', 'seafood'],
  fig_2: ['Figue', 'fruits'],
  fig: ['Figue', 'fruits'],
  eggplant: ['Aubergine', 'vegetables'],
  egg: ['Œuf', 'dairy'],
  eclair: ['Éclair', 'desserts'],
  dumpling: ['Madeleine', 'desserts'],
  'drop-of-blood': ['Protections hygiéniques', 'other'],
  doughnut_3: ['Doughnut', 'desserts'],
  doughnut_2: ['Doughnut', 'desserts'],
  doughnut: ['Doughnut', 'desserts'],
  cutlet: ['Escalope', 'meat'],
  cupcake: ['Cupcake', 'desserts'],
  cucumber_2: ['Concombre', 'vegetables'],
  cucumber: ['Concombre', 'vegetables'],
  croissant: ['Croissant', 'desserts'],
  cranberries: ['Canneberges', 'fruits'],
  cracker: ['Cracker', 'snacks'],
  crab: ['Crabe', 'seafood'],
  cotton_candy_2: ['Barbe à papa', 'desserts'],
  cotton_candy: ['Barbe à papa', 'desserts'],
  corn: ['Maïs', 'vegetables'],
  cookie_3: ['Cookie', 'desserts'],
  cookie_1: ['Cookie', 'desserts'],
  cookie5: ['Cookie', 'desserts'],
  cookie4: ['Cookie', 'desserts'],
  cookie: ['Cookie', 'desserts'],
  cognac: ['Cognac', 'beverages'],
  coffee_pot: ['Cafetière', 'beverages'],
  coffee_bean: ['Grains de café', 'nuts'],
  coffee: ['Café', 'beverages'],
  coconut_split_2: ['Noix de coco (tranchée)', 'fruits'],
  coconut_split: ['Noix de coco (tranchée)', 'fruits'],
  coconut: ['Noix de coco', 'fruits'],
  cocoa: ['Cacao', 'nuts'],
  cocktail: ['Cocktail', 'beverages'],
  cinnamon: ['Cannelle', 'nuts'],
  chopsticks_bowl: ['Bol avec des baguettes', 'other'],
  chopsticks: ['Sauce soja', 'condiments'],
  chocolate_chip_cookie: ['Cookie aux pépites de chocolat', 'desserts'],
  chocolate_bonbon: ['Bonbon au chocolat', 'desserts'],
  chocolate_bar: ['Barre de chocolat', 'desserts'],
  chocolate: ['Chocolat', 'desserts'],
  chili_pepper: ['Piment', 'vegetables'],
  chickpeas: ['Pois chiches', 'vegetables'],
  chicken_leg_fried: ['Cuisse de poulet frite', 'meat'],
  chicken_leg: ['Cuisse de poulet', 'meat'],
  chestnut: ['Châtaigne', 'nuts'],
  cherry_tomatoes: ['Tomates cerises', 'vegetables'],
  cherries: ['Cerises', 'fruits'],
  cheese: ['Fromage', 'dairy'],
  champagne: ['Champagne', 'beverages'],
  cellery: ['Céleri', 'vegetables'],
  cauliflower: ['Chou-fleur', 'vegetables'],
  cassava: ['Manioc', 'vegetables'],
  cashew_nuts: ['Noix de cajou', 'nuts'],
  carrot: ['Carotte', 'vegetables'],
  caramel_apple: ['Pomme au caramel', 'desserts'],
  cantaloupe_slice: ['Melon (tranché)', 'fruits'],
  cantaloupe: ['Melon', 'fruits'],
  'canned-food': ['Sauce en conserve', 'condiments'],
  candy_cane: ['Canne en sucre', 'desserts'],
  candy: ['Bonbon', 'desserts'],
  cake_slice_nuts: ['Part de gâteau aux noix', 'desserts'],
  cake_slice: ['Part de gâteau', 'desserts'],
  cake: ['Gâteau', 'desserts'],
  cabbage: ['Chou', 'vegetables'],
  butter: ['Beurre', 'dairy'],
  bun: ['Petit pain', 'grains'],
  bubblegum_machine: ['Distributeur de chewing-gum', 'snacks'],
  bubblegum: ['Chewing-gum', 'snacks'],
  brown_bread: ['Pain complet', 'grains'],
  broccoli: ['Brocoli', 'vegetables'],
  bread_slice: ['Tranche de pain', 'grains'],
  bread: ['Pain', 'grains'],
  brazil_nuts: ['Noix du Brésil', 'nuts'],
  'bowl-with-spoon': ['Yaourts', 'dairy'],
  bottle_wine: ['Bouteille de vin', 'beverages'],
  bottle_scotch_2: ['Bouteille de scotch', 'beverages'],
  bottle_scotch: ['Bouteille de scotch', 'beverages'],
  bottle_gallon: ['Grosse bouteille', 'other'],
  blueberries: ['Myrtilles', 'fruits'],
  blackberry: ['Mûre', 'fruits'],
  biscuit: ['Biscuit', 'snacks'],
  biscotti: ['Biscotti', 'snacks'],
  birthday_cake: ["Gâteau d'anniversaire", 'desserts'],
  bell_pepper_split: ['Poivron (tranché)', 'vegetables'],
  bell_pepper: ['Poivron', 'vegetables'],
  beetroot: ['Betterave', 'vegetables'],
  beef: ['Bœuf', 'meat'],
  beans: ['Haricots', 'vegetables'],
  banana_split: ['Banana split', 'desserts'],
  banana_peeled: ['Banane (pelée)', 'fruits'],
  banana: ['Banane', 'fruits'],
  bacon: ['Bacon', 'meat'],
  avocado_split: ['Avocat (tranché)', 'fruits'],
  avocado: ['Avocat', 'fruits'],
  asparagus: ['Asperge', 'vegetables'],
  artichoke: ['Artichaut', 'vegetables'],
  apple_split: ['Pomme (tranchée)', 'fruits'],
  apple_green_split: ['Pomme verte (tranchée)', 'fruits'],
  apple_green: ['Pomme verte', 'fruits'],
  apple: ['Pomme', 'fruits'],
  almonds: ['Amandes', 'nuts'],
  almond: ['Amande', 'nuts'],
} as const;

export type FoodIcons = keyof typeof ICON_FONT_MAP;

// Helper function to get CSS class name for an icon
export const getIconClass = (iconId: FoodIcons | undefined): string => {
  if (!iconId) return 'food-icon';
  return `food-icon food-icon-${iconId}`;
};

export const getIconData = (iconId: FoodIcons): FoodIconData | undefined => {
  const icon = ICON_FONT_MAP[iconId];
  if (!icon) return undefined;

  const [name, category] = icon;
  return { id: iconId, name, category };
};

// Export the data
export const ICON_DATA: FoodIconData[] = Object.entries(ICON_FONT_MAP)
  .map(([id, [name, category]]) => ({
    id,
    name,
    category: CATEGORY_TRANSLATIONS[category],
  }))
  .toSorted((a, b) => a.name.localeCompare(b.name));
