/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedProductsRouteImport } from './routes/_authed/products'
import { Route as AuthedDashboardRouteImport } from './routes/_authed/dashboard'
import { Route as AuthedHouseholdIndexRouteImport } from './routes/_authed/household/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthedHouseholdNewRouteImport } from './routes/_authed/household/new'
import { Route as AuthedHouseholdJoinIdRouteImport } from './routes/_authed/household/join.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedProductsRoute = AuthedProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedHouseholdIndexRoute = AuthedHouseholdIndexRouteImport.update({
  id: '/household/',
  path: '/household/',
  getParentRoute: () => AuthedRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedHouseholdNewRoute = AuthedHouseholdNewRouteImport.update({
  id: '/household/new',
  path: '/household/new',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedHouseholdJoinIdRoute = AuthedHouseholdJoinIdRouteImport.update({
  id: '/household/join/$id',
  path: '/household/join/$id',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/products': typeof AuthedProductsRoute
  '/household/new': typeof AuthedHouseholdNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/household': typeof AuthedHouseholdIndexRoute
  '/household/join/$id': typeof AuthedHouseholdJoinIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/products': typeof AuthedProductsRoute
  '/household/new': typeof AuthedHouseholdNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/household': typeof AuthedHouseholdIndexRoute
  '/household/join/$id': typeof AuthedHouseholdJoinIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/_authed/products': typeof AuthedProductsRoute
  '/_authed/household/new': typeof AuthedHouseholdNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_authed/household/': typeof AuthedHouseholdIndexRoute
  '/_authed/household/join/$id': typeof AuthedHouseholdJoinIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/products'
    | '/household/new'
    | '/api/auth/$'
    | '/household'
    | '/household/join/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/products'
    | '/household/new'
    | '/api/auth/$'
    | '/household'
    | '/household/join/$id'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/login'
    | '/_authed/dashboard'
    | '/_authed/products'
    | '/_authed/household/new'
    | '/api/auth/$'
    | '/_authed/household/'
    | '/_authed/household/join/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/products': {
      id: '/_authed/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AuthedProductsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/household/': {
      id: '/_authed/household/'
      path: '/household'
      fullPath: '/household'
      preLoaderRoute: typeof AuthedHouseholdIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/household/new': {
      id: '/_authed/household/new'
      path: '/household/new'
      fullPath: '/household/new'
      preLoaderRoute: typeof AuthedHouseholdNewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/household/join/$id': {
      id: '/_authed/household/join/$id'
      path: '/household/join/$id'
      fullPath: '/household/join/$id'
      preLoaderRoute: typeof AuthedHouseholdJoinIdRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedProductsRoute: typeof AuthedProductsRoute
  AuthedHouseholdNewRoute: typeof AuthedHouseholdNewRoute
  AuthedHouseholdIndexRoute: typeof AuthedHouseholdIndexRoute
  AuthedHouseholdJoinIdRoute: typeof AuthedHouseholdJoinIdRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedProductsRoute: AuthedProductsRoute,
  AuthedHouseholdNewRoute: AuthedHouseholdNewRoute,
  AuthedHouseholdIndexRoute: AuthedHouseholdIndexRoute,
  AuthedHouseholdJoinIdRoute: AuthedHouseholdJoinIdRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
