/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedRecipesRouteImport } from './routes/_authed/recipes'
import { Route as AuthedProductsRouteImport } from './routes/_authed/products'
import { Route as AuthedDashboardRouteImport } from './routes/_authed/dashboard'
import { Route as AuthedRecipesIndexRouteImport } from './routes/_authed/recipes/index'
import { Route as AuthedHouseholdIndexRouteImport } from './routes/_authed/household/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthedRecipesNewRouteImport } from './routes/_authed/recipes/new'
import { Route as AuthedHouseholdNewRouteImport } from './routes/_authed/household/new'
import { Route as AuthedRecipesRecipeIdIndexRouteImport } from './routes/_authed/recipes/$recipeId/index'
import { Route as AuthedRecipesRecipeIdEditRouteImport } from './routes/_authed/recipes/$recipeId/edit'
import { Route as AuthedHouseholdJoinIdRouteImport } from './routes/_authed/household/join.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRecipesRoute = AuthedRecipesRouteImport.update({
  id: '/recipes',
  path: '/recipes',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedProductsRoute = AuthedProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedRecipesIndexRoute = AuthedRecipesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRecipesRoute,
} as any)
const AuthedHouseholdIndexRoute = AuthedHouseholdIndexRouteImport.update({
  id: '/household/',
  path: '/household/',
  getParentRoute: () => AuthedRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRecipesNewRoute = AuthedRecipesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthedRecipesRoute,
} as any)
const AuthedHouseholdNewRoute = AuthedHouseholdNewRouteImport.update({
  id: '/household/new',
  path: '/household/new',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedRecipesRecipeIdIndexRoute =
  AuthedRecipesRecipeIdIndexRouteImport.update({
    id: '/$recipeId/',
    path: '/$recipeId/',
    getParentRoute: () => AuthedRecipesRoute,
  } as any)
const AuthedRecipesRecipeIdEditRoute =
  AuthedRecipesRecipeIdEditRouteImport.update({
    id: '/$recipeId/edit',
    path: '/$recipeId/edit',
    getParentRoute: () => AuthedRecipesRoute,
  } as any)
const AuthedHouseholdJoinIdRoute = AuthedHouseholdJoinIdRouteImport.update({
  id: '/household/join/$id',
  path: '/household/join/$id',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/products': typeof AuthedProductsRoute
  '/recipes': typeof AuthedRecipesRouteWithChildren
  '/household/new': typeof AuthedHouseholdNewRoute
  '/recipes/new': typeof AuthedRecipesNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/household': typeof AuthedHouseholdIndexRoute
  '/recipes/': typeof AuthedRecipesIndexRoute
  '/household/join/$id': typeof AuthedHouseholdJoinIdRoute
  '/recipes/$recipeId/edit': typeof AuthedRecipesRecipeIdEditRoute
  '/recipes/$recipeId': typeof AuthedRecipesRecipeIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/products': typeof AuthedProductsRoute
  '/household/new': typeof AuthedHouseholdNewRoute
  '/recipes/new': typeof AuthedRecipesNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/household': typeof AuthedHouseholdIndexRoute
  '/recipes': typeof AuthedRecipesIndexRoute
  '/household/join/$id': typeof AuthedHouseholdJoinIdRoute
  '/recipes/$recipeId/edit': typeof AuthedRecipesRecipeIdEditRoute
  '/recipes/$recipeId': typeof AuthedRecipesRecipeIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/_authed/products': typeof AuthedProductsRoute
  '/_authed/recipes': typeof AuthedRecipesRouteWithChildren
  '/_authed/household/new': typeof AuthedHouseholdNewRoute
  '/_authed/recipes/new': typeof AuthedRecipesNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_authed/household/': typeof AuthedHouseholdIndexRoute
  '/_authed/recipes/': typeof AuthedRecipesIndexRoute
  '/_authed/household/join/$id': typeof AuthedHouseholdJoinIdRoute
  '/_authed/recipes/$recipeId/edit': typeof AuthedRecipesRecipeIdEditRoute
  '/_authed/recipes/$recipeId/': typeof AuthedRecipesRecipeIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/products'
    | '/recipes'
    | '/household/new'
    | '/recipes/new'
    | '/api/auth/$'
    | '/household'
    | '/recipes/'
    | '/household/join/$id'
    | '/recipes/$recipeId/edit'
    | '/recipes/$recipeId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/products'
    | '/household/new'
    | '/recipes/new'
    | '/api/auth/$'
    | '/household'
    | '/recipes'
    | '/household/join/$id'
    | '/recipes/$recipeId/edit'
    | '/recipes/$recipeId'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/login'
    | '/_authed/dashboard'
    | '/_authed/products'
    | '/_authed/recipes'
    | '/_authed/household/new'
    | '/_authed/recipes/new'
    | '/api/auth/$'
    | '/_authed/household/'
    | '/_authed/recipes/'
    | '/_authed/household/join/$id'
    | '/_authed/recipes/$recipeId/edit'
    | '/_authed/recipes/$recipeId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/recipes': {
      id: '/_authed/recipes'
      path: '/recipes'
      fullPath: '/recipes'
      preLoaderRoute: typeof AuthedRecipesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/products': {
      id: '/_authed/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AuthedProductsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/recipes/': {
      id: '/_authed/recipes/'
      path: '/'
      fullPath: '/recipes/'
      preLoaderRoute: typeof AuthedRecipesIndexRouteImport
      parentRoute: typeof AuthedRecipesRoute
    }
    '/_authed/household/': {
      id: '/_authed/household/'
      path: '/household'
      fullPath: '/household'
      preLoaderRoute: typeof AuthedHouseholdIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/recipes/new': {
      id: '/_authed/recipes/new'
      path: '/new'
      fullPath: '/recipes/new'
      preLoaderRoute: typeof AuthedRecipesNewRouteImport
      parentRoute: typeof AuthedRecipesRoute
    }
    '/_authed/household/new': {
      id: '/_authed/household/new'
      path: '/household/new'
      fullPath: '/household/new'
      preLoaderRoute: typeof AuthedHouseholdNewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/recipes/$recipeId/': {
      id: '/_authed/recipes/$recipeId/'
      path: '/$recipeId'
      fullPath: '/recipes/$recipeId'
      preLoaderRoute: typeof AuthedRecipesRecipeIdIndexRouteImport
      parentRoute: typeof AuthedRecipesRoute
    }
    '/_authed/recipes/$recipeId/edit': {
      id: '/_authed/recipes/$recipeId/edit'
      path: '/$recipeId/edit'
      fullPath: '/recipes/$recipeId/edit'
      preLoaderRoute: typeof AuthedRecipesRecipeIdEditRouteImport
      parentRoute: typeof AuthedRecipesRoute
    }
    '/_authed/household/join/$id': {
      id: '/_authed/household/join/$id'
      path: '/household/join/$id'
      fullPath: '/household/join/$id'
      preLoaderRoute: typeof AuthedHouseholdJoinIdRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRecipesRouteChildren {
  AuthedRecipesNewRoute: typeof AuthedRecipesNewRoute
  AuthedRecipesIndexRoute: typeof AuthedRecipesIndexRoute
  AuthedRecipesRecipeIdEditRoute: typeof AuthedRecipesRecipeIdEditRoute
  AuthedRecipesRecipeIdIndexRoute: typeof AuthedRecipesRecipeIdIndexRoute
}

const AuthedRecipesRouteChildren: AuthedRecipesRouteChildren = {
  AuthedRecipesNewRoute: AuthedRecipesNewRoute,
  AuthedRecipesIndexRoute: AuthedRecipesIndexRoute,
  AuthedRecipesRecipeIdEditRoute: AuthedRecipesRecipeIdEditRoute,
  AuthedRecipesRecipeIdIndexRoute: AuthedRecipesRecipeIdIndexRoute,
}

const AuthedRecipesRouteWithChildren = AuthedRecipesRoute._addFileChildren(
  AuthedRecipesRouteChildren,
)

interface AuthedRouteChildren {
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedProductsRoute: typeof AuthedProductsRoute
  AuthedRecipesRoute: typeof AuthedRecipesRouteWithChildren
  AuthedHouseholdNewRoute: typeof AuthedHouseholdNewRoute
  AuthedHouseholdIndexRoute: typeof AuthedHouseholdIndexRoute
  AuthedHouseholdJoinIdRoute: typeof AuthedHouseholdJoinIdRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedProductsRoute: AuthedProductsRoute,
  AuthedRecipesRoute: AuthedRecipesRouteWithChildren,
  AuthedHouseholdNewRoute: AuthedHouseholdNewRoute,
  AuthedHouseholdIndexRoute: AuthedHouseholdIndexRoute,
  AuthedHouseholdJoinIdRoute: AuthedHouseholdJoinIdRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
